version: '3.7'

networks:
  fluxocaixa:
    external: true

services:
  redis:
    image: redis
    hostname: fluxocaixa.redis
    container_name: fluxocaixa.redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    networks:
      fluxocaixa:
        ipv4_address: 172.19.0.102